name: hyper_algo_search_3_ways
description: A Dart package providing various search algorithms with performance measurement for Flutter and Dart applications.
version: 1.0.0
repository: https://github.com/Bexruzbek-dev/algo
homepage: https://github.com/Bexruzbek-dev/algo

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0

license: MIT


